export enum Routes {
  AUTH = 'auth',
  USERS = 'users',
  CONVERSATIONS = 'conversations',
  PARTICIPANTS = 'participants',
  MESSAGES = 'messages',
  USERS_PROFILES = 'users/profiles',
  FRIENDS = 'friends',
  FRIENDS_REQUEST = 'friends/requests',
}
export enum Services {
  AUTH = 'AUTH_SERVICE',
  USERS = 'USERS_SERVICE',
  CONVERSATIONS = 'CONVERSATIONS_SERVICE',
  PARTICIPANTS = 'PARTICIPANTS_SERVICE',
  MESSAGES = 'MESSAGES_SERVICE',
  GATEWAY_SESSION_MANAGER = 'GATEWAY_SESSION_MANAGER',
  USERS_PROFILES = 'USERS_PRORFILES_SERVICE',
  FRIENDS_SERVICES = 'FRIENDS_SERVICE',
  FRIENDS_REQUEST_SERVICES = 'FRIENDS_REQUEST_SERVICES',
}
